### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by iboboc** [lluiscab/MPQTT#7]
Hi,

After install, after service start, I get an error 
 ERROR mqtt_async_client::client::client > IoTask: Error connecting: Connection refused (os error 111)
Any idea where to look into?

Thanks.

**Comment by lluiscab** [comment]
Seems to be an issue connecting to the MQTT server. I'd check the server ip and port, make sure the device that's running MPQTT can ping the device hosting the MQTT server.
